return {
	"nvim-treesitter/nvim-treesitter",
	branch = "main",
	build = ":TSUpdate",
	config = function()
		vim.opt.runtimepath = vim.opt.runtimepath + "~/.local/share/nvim/site"
		require("nvim-treesitter").setup()
		require("nvim-treesitter").install({
			"arduino",
			"asm",
			"awk",
			"bash",
			"bibtex",
			"c",
			"c_sharp",
			"cmake",
			"cpp",
			"css",
			"csv",
			"desktop",
			"diff",
			"dockerfile",
			"git_config",
			"git_rebase",
			"gitattributes",
			"gitcommit",
			"gitignore",
			"go",
			"html",
			"java",
			"javascript",
			"jq",
			"jsdoc",
			"json",
			"kotlin",
			"latex",
			"lua",
			"luadoc",
			"luap",
			"make",
			"markdown",
			"markdown_inline",
			"meson",
			"ninja",
			"nix",
			"perl",
			"php",
			"powershell",
			"printf",
			"python",
			"regex",
			"query",
			"rust",
			"sql",
			"systemverilog",
			"toml",
			"tsx",
			"typescript",
			"vhdl",
			"vim",
			"vimdoc",
			"xml",
			"yaml",
			"zsh",
		})
		vim.treesitter.language.register("latex", "plaintex")
		vim.treesitter.language.register("systemverilog", "v")
		vim.api.nvim_create_autocmd("FileType", {
			pattern = { "*" },
			callback = function()
				vim.treesitter.start()
			end,
		})
	end,
}
