name: ubuntu-arm
on:
  workflow_dispatch:
jobs:
  install:
    timeout-minutes: 360
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        timeout-minutes: 360
        uses: actions/checkout@v4
      - name: Full install
        timeout-minutes: 360
        run: ./test.sh
